---
# - debug:
#     msg: "TOP: {{ config_level }}, {{ outer_item.key }}: {{ outer_item.value }}"

# - debug: 
#     msg: "{{ config_level, orig[config_level] }}"

- set_fact:
    orig: "{{ orig | combine(new_item, recursive=true) }}"
  vars: 
    new_item: "{{ { config_level :{outer_item.key: outer_item.value|vault(vault_key) } } }}"
    # new_item: "{ '{{ outer_item.key }}': '{{ outer_item.value|vault(vault_key) }}' }"

# - name: ONE
#   set_fact:
#     orig: "{{ "{ 'key': 'value' }" }}

# - debug: 
#     msg: "{{ orig }}"
