---
- name: Ensure directoy is empty
  ansible.builtin.file:
    path: "/tmp/git-secrets"
    state: absent
  ignore_errors: true

- name: Create folder
  ansible.builtin.file:
    path: "/tmp/git-secrets"
    state: directory

- name: Checkout repo
  shell: "{{ item }}"
  args:
    chdir: "/tmp/git-secrets"
  with_items:
    - rm -rf .git
    - git clone "{{ acm_git | regex_replace('(https:\/\/)', giturl) }}" . 
    - git config user.name "ZTP ROBO"
    - git config user.email ztp@ztp.com

- name: Read Secrets file
  ansible.builtin.include_vars:
    dir: "/tmp/git-secrets/"
    name: configs_in_git
    depth: 1
    extensions:
      - 'json'

- name: Merge secrets file with new values
  set_fact:
    orig: "{{ orig | combine(configs_in_git) }}"

- name: Save to JSON
  copy:
    content: "{{ orig | to_nice_json }}"
    dest: "/tmp/git-secrets/kube-secrets.json"

- name: Commit changes and push file to repo
  shell: "{{ item }}"
  args:
    chdir: "/tmp/git-secrets"
  with_items:
    - git add /tmp/git-secrets/kube-secrets.json
    - git commit -a -m "Ansible | Update secrets"
    - git push 
  ignore_errors: true