- name: Save secret section level
  set_fact: 
    config_level: "{{ item.key }}"

- name: Iterate secret section to encrypt input values
  include_tasks: encrypt-vars.yaml
  loop: "{{ item.value | dict2items }}"
  loop_control:
    loop_var: outer_item

# - set_fact:
#     "{{ item.key }}": "{{ item.value }}"
